# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc68e3df53336c7684a0172befeee53af577454d8d7120051b6a80947f7bb99b3d4f28466cdb85c14890268372d8f09395f3f62d46ebf4ddd44de36d2d6f1108

test:
  secret_key_base: 058262297d1b356de7beb7c2204f414d106b25fb664d62b97979c00c596039e108bb5ff80c25c3fef98161dfa5923bb9b2af6b303a5628964879d2ceae572bbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
